### ISSUE TITLE
[GNOME 3.18] TypeError: St.Table is not a constructor (again ;)

### ISSUE THREAD

**Issue by Bob131** [awamper/web-search-dialog#12]
See awamper/wikipedia-search-provider#12, it seems to apply to this extension as well

**Comment by mtompkins** [comment]
+1

Looking forward to the >= 3.18 update. This is such a handy little extension.

**Comment by djmaze** [comment]
Fix available in #13.

**Comment by teskew-rms** [comment]
Is there any reason that this change has not been merged?

**Comment by djmaze** [comment]
Maybe because of this inadequacy in the PR? 

> There's most likely a better way of handling the process-working.svg -> classic-process-working.svg name change than removing it altogether :-)

**Comment by awamper** [comment]
2ba1f1b6
