### ISSUE TITLE
How do I install it? 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [awamper/web-search-dialog#15]
There is no .md or documentation for installing it. I am running Ubuntu 15.10 with Gnome(not unity). I want this extension.

**Comment by leon1101** [comment]
clone this repo to `/usr/share/gnome-shell/extensions/web_search_dialog@awamper.gmail.com/`, restart gnome-shell (alt + f2 -> r + enter), open tweak tool, enable extension
