### ISSUE TITLE
Dash integration

### ISSUE THREAD

**Issue by varemenos** [awamper/web-search-dialog#2]
Is there a way to integrate this into the Dash? Wouldn't that be way better?
What i mean is instead of using super+space to reveal the current dialog box to use the Dash's search dialog.

**Comment by khalido** [comment]
Old discussion, but would love it if I could invoke it directly from gnome-shell (or dash). ideally using a keyword, so:
 
1. press super to open gnome search box
2. type g "search term goes here"

instead of having to use ctrl-space.
