### ISSUE TITLE
Gnome 3.24 and settings error

### ISSUE THREAD

**Issue by mammuth** [awamper/web-search-dialog#20]
The following error occurs, when opening the extension settings via the Tweak Tools with Gnome 3.24 on Arch:
`TypeError: redeclaration of let engines_list
Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49`

Also I set the shell-version in the `manifest.json` to 3.24

**Comment by Pete-Hamlin** [comment]
I managed to get mine working in 3.24 with the following tweaks to the source (located `$HOME/.local/share/gnome-shell/extensions/web_search_dialog@awamper.gmail.com`):

* Open `prefs.js` in your editor of choice and change the variables at lines 461, 464, 465 from `engines_list` to `engine_list`
* Make sure your `metadata.json` shell version is set to 3.24.

Save and check you can load your preferences menu through the tweak tool. If you can, then reboot and you should (hopefully) be able to use the dialog menu again.

Good luck!
