### ISSUE TITLE
Allow current search engines to be edited

### ISSUE THREAD

**Issue by mammuth** [awamper/web-search-dialog#21]
Currently, it seems like one can only add or delete search engines. There seems to be no way to edit a created one, which might be helpful sometimes.

**Comment by clockworkpc** [comment]
I can't even delete a created one.

**Comment by AmNe5iA** [comment]
Agreed.  I have to delete everyone and then re-add them as https links every time I install this on a new desktop.

**Comment by awamper** [comment]
9afc960

**Comment by AmNe5iA** [comment]
Awesome!
