### ISSUE TITLE
Can't install from extensions.gnome.org

### ISSUE THREAD

**Issue by mammuth** [awamper/web-search-dialog#25]
I just tried to install the extension via extensions.gnome.org, but the extension gets removed directly after adding it (or probably never gets added).

Directly adding the latest code (https://github.com/awamper/web-search-dialog/commit/d301d9c0e0902648230cf8c156414e1c1e6912ec) as an extension works fine. Is the latest code already published on extensions.gnome.org?

I'm on gnome-shell 3.24.2

**Comment by Hanzei** [comment]
@mammuth I think extensions.gnome.org didn't got an update.
@awamper Can you confirm?

**Comment by awamper** [comment]
updated
