### ISSUE TITLE
Please, can you fix the extension for GNOME version 3.24.2?

### ISSUE THREAD

**Issue by Warmuser** [awamper/web-search-dialog#27]
I can install the extension from the GNOME store and the settings box appartently work, but the extension doesn't search anything..

My specs:

Desktop Environment: GNOME v3.24.2
Distro: Manjaro v17.0.2
Kernel Linux v4.9.40-1-MANJARO
Shell: bash v4.4.12
I run the OS on VMWare Workstation 12 Player
My machine is based on a i5 configuration.

**Comment by Hanzei** [comment]
@awamper didn't update the extenstion yet. See #25

**Comment by awamper** [comment]
I updated it on august 6.

**Comment by awamper** [comment]
@Warmuser try to change hotkey.

**Comment by Warmuser** [comment]
@awamper what hotkey should I use?

**Comment by awamper** [comment]
Just any hotkey.

**Comment by Warmuser** [comment]
Uhm, I tried but it doesn't work.. I will try to disable all the extensions and verify If something conflicts with the your extension. See you later. :)
