### ISSUE TITLE
Extension interferes with gnome 3.26.2 lock screen

### ISSUE THREAD

**Issue by AmNe5iA** [awamper/web-search-dialog#30]
This extension inhibits entering a password in the gnome lock screen.  Worse still it completes a google search (or whatever the default search engine is set to..)of the typed password attempt!  This does not become apparent until after the screen is finally unlocked.

I'm running Debian testing distribution.

**Comment by Bob131** [comment]
+1, can replicate:

```
fedora-release-27-1.noarch
gnome-shell-3.26.2-1.fc27.x86_64
```

**Comment by zelvick** [comment]
+1 replicated , same issue as #29

**Comment by AmNe5iA** [comment]
Brilliant.  Upgraded and extension re-enabled.  Thanks
