### ISSUE TITLE
Closing the extension

### ISSUE THREAD

**Issue by bushwakko** [awamper/web-search-dialog#32]
User story: 

User runs Arch with gnome 3.26.2. Everything is so updated that it's almost like the desktop has a new from factory smell.

Sometimes I click ctrl + space on accident, or I regret the decision and want to close the dialog. Since I have my hands over alt and space (I just clicked it) I try that again, expecting it to close. It doesn't. Clicking with mouse (I conveniently had one hand there) anywhere on the screen outside of the dialog does nothing (while I somehow expect it to close it). I don't really reach want to reach for the ESC-key, as it's on the outer rim my keyboard, the furthest possible distance away from my mouse hand, and  maximal extension for the left hand.

User wants to close the dialog with the same bind that opens it. User wants to expend as little energy as possible on moving hands around keyboard. User also wants to close dialog by clicking the mouse anywhere outside of the dialog.

From this dramatic user report it should be clear that this is something worth spending time on.

**Comment by noerw** [comment]
Hey, I actually implemented exactly this in #31. I don't know if awamper has released a new version yet with those changes.
Installing from github will get you those Features

**Comment by awamper** [comment]
I uploaded it to the website on the same day. @bushwakko  check https://extensions.gnome.org for update or install from the master branch.

**Comment by bushwakko** [comment]
Hi, that was fast!

Clicking with the mouse outside of the dialog doesn't close it though, this is still a bit weird and could easily be fixed I assume. Do you want to re-open this or new issue?
